<table class="table">
	<thead>
    	<tr>
        	<th>Hora</th>
           <th>Asunto</th>
        </tr>
    </thead>
    <tbody>
    	<tr>
        	<td>AAAAA</td>
           <td>bbbbb</td>
        </tr>
        <tr>
        	<td>AAAAA</td>
           <td>bbbbb</td>
        </tr>
        <tr>
        	<td>AAAAA</td>
           <td>bbbbb</td>
        </tr>
    </tbody>
</table>